spring.application.name=Journal App
#spring.data.mongodb.uri= mongodb+srv://jindalravi379:Qcfnt7bYeidNNO9e@cluster0.xck1ffx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri = mongodb://localhost:27017
spring.data.mongodb.auto-index-creation= true
management.endpoints.web.exposure.include=health,info,metrics,beans











# server still local,But db is hosted on AWS cloud
#spring.data.mongodb.host= localhost
#spring.data.mongodb.port= 27017
spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword



spring.main.allow-circular-references = true
#spring.data.mongodb.uri= mongodb+srv://jindalravi379mcd:jJ26qKX0c3Fe7ZAt@cluster0.wnbne.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#MongoDb userID,Password on website ->jindalravi379+mcd@gmail.com, Ravi@4196
# Mongodb username=jindalravi379 and password = Qcfnt7bYeidNNO9e to create
# uri: mongodb+srv://jindalravi379:Qcfnt7bYeidNNO9e@cluster0.xck1ffx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0


